name: Deploy to S3

on:
  push:
    branches: [ main ]   # CI/CD fires on pushes to main

# Required so the OIDC token can be minted for your job
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci            # faster & repeatable

    - name: Install Grunt CLI globally
      run: npm install -g grunt-cli

    - name: Run Grunt build
      run: grunt build

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::247310156864:role/aws_uploader
        aws-region: us-east-1
        role-session-name: github-actions-${{ github.run_id }}

    - name: Sync files to S3
      run: |
        aws s3 sync build/ s3:// ${{secrets.AWS_S3_BUCKET}} --delete --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}